### PR TITLE
Some tweaks for tone platform

### PR DESCRIPTION
**Pull request by sjllls**
Already tested.

### CODE REVIEW

**Comment by sjllls** [comment]
The system lag on dora has disppered by disabling some thermal configs. Now we could get normal performance of MSM8996 by using EAS.
Screenshot_20190716-231804_Geekbench_4

**Comment by lazerl0rd** [comment]
Thanks, will pick from here and keep your authorship.

**Comment by lazerl0rd** [comment]
@sjllls if you look at my rebase, I did things a bit differently to you tho:
1) I don't think the vendor treble thing is good for SODP (or ZfSODP in that case), therefore I didn't add it in.
2) I used a different EM to which IIRC had better efficiency and performance.
3) The min panel brightness seems great, but I'd prolly co-author that with you to fix maple's too.
4) GPU timeout was done all SoCs together.

**Comment by lazerl0rd** [comment]
Not sure why you turned off thermal too, and libperfmanager will prolly use @celtare21's implementation.

**Comment by lazerl0rd** [comment]
Not sure why you turned off thermal too, and libperfmanager will prolly use @celtare21's implementation.

**Comment by sjllls** [comment]
> @sjllls if you look at my rebase, I did things a bit differently to you tho:
> 
> 1. I don't think the vendor treble thing is good for SODP (or ZfSODP in that case), therefore I didn't add it in.
> 2. I used a different EM to which IIRC had better efficiency and performance.
> 3. The min panel brightness seems great, but I'd prolly co-author that with you to fix maple's too.
> 4. GPU timeout was done all SoCs together.

I am testing whether the EM or thermal cause system lag. After I find the reason, I will push PR again. About brightness you need check it on maple. 
Thanks for your advices !

**Pull request closed without merging**
